### ISSUE TITLE
Parabéns pelo projeto

### ISSUE THREAD

**Issue by zaratt** [osvaldokalvaitir/react-native-saas#3]
Eu estava estudando esse projeto, mas desisti depois de uma série de erros. Que legal. Estou com uma dúvida: A seleção de times na esquerda era um pacote depreciado. Eu me recordo que na época tive muitas dificuldades para ajustar. Vc está usando o mesmo pacote que o Diego ensina nos vídeos ou você encontrou outro?

**Comment by osvaldokalvaitir** [comment]
Bom dia Alan!!

Faz tempo que fiz este projeto, não lembro direito!

Mas parece que era algo assim mesmo, o pacote estava depreciado, acho que usei outro!

Abraços
________________________________
De: Alan Ribeiro <notifications@github.com>
Enviado: sábado, 19 de setembro de 2020 10:18
Para: osvaldokalvaitir/react-native-saas <react-native-saas@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: [osvaldokalvaitir/react-native-saas] Parabéns pelo projeto (#3)


Eu estava estudando esse projeto, mas desisti depois de uma série de erros. Que legal. Estou com uma dúvida: A seleção de times na esquerda era um pacote depreciado. Eu me recordo que na época tive muitas dificuldades para ajustar. Vc está usando o mesmo pacote que o Diego ensina nos vídeos ou você encontrou outro?
